(BEGIN)
    (BACKGROUND_ON 1)
    
    (PLAYER_SPRITE_SCALE 0.05)
    
    (PLAYER_INIT_POS_X 0.3)
    (PLAYER_INIT_POS_Y 0.2)
    
    (PLAYER_INIT_ONGROUND 1)
    (PLAYER_INIT_THRUSTON 0)
    (PLAYER_INIT_RUNNING 0)
    
    (PLAYER_INIT_THRUST_MAGN 1.6)
    (PLAYER_INIT_RUN_SPEED 0.005)
    (PLAYER_INIT_RUN_ANGLE 0.1)
    
    (PLAYER_CHANGE_ANGLE_SENSITIVITY 2.0)
    
    (PLAYER_ENERGY_DEPLETION_RATE 0.01)
    (PLAYER_ENERGY_RECHARGE_RATE 0.005)
    
    (CAMERA_FOLLOW_PLAYER 1)
    (CAMERA_ZOOM_ON 1)
    (CAMERA_INIT_ZOOM 1.0)
    (CAMERA_INIT_POS_X -0.4)
    (CAMERA_INIT_POS_Y -0.4)
    
    (CAMERA_CURRENT_WIDTH 1)
    (CAMERA_CURRENT_HEIGHT 1)
    
    (WORLD_INIT_AIR_RESISTANCE_X 0.05)
    (WORLD_INIT_AIR_RESISTANCE_Y 0.02)
    
    (TEST_ANGLE_ROTATE 0.5)
(END)
